name: Publish new package version on NuGet

on:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  call-dotnet_nuget_build_publish:
    uses: hcspieker/shared-build-components/.github/workflows/dotnet_nuget_build_publish.yml@v1.2.0-alpha.1
    with:
      dotnet-version: |
        10.0.x
        9.0.x
        8.0.x
      build-filter: 'SimpleLinkShrinkLibrary/SimpleLinkShrinkLibrary.sln'
      enable-tests: 'false'
      environment-name: ''
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}
