name: Publish new package version on NuGet

on:
  push:
    tags:
      - 'v*.*.*'
      
env:
  BUILD_FILTER: 'SimpleLinkShrinkLibrary/SimpleLinkShrinkLibrary.sln'
  BUILD_CONFIG: 'Release'
  PACKAGES_DIR: 'NuGetPackages'
  ARTIFACT_NAME: 'CreatedNuGetPackages'
  DOTNET_VERSION: |
    10.0.x
    9.0.x
    8.0.x

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted TAG: $TAG"
        echo "Extracted VERSION: $VERSION"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ env.BUILD_FILTER }}

    - name: Build
      shell: bash
      run: dotnet build ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore /p:Version=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }} /p:InformationalVersion=${{ env.VERSION }}+sha.${GITHUB_SHA:0:7}
      
    - name: NuGet Pack
      shell: bash
      run: dotnet pack ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore -o ${{ env.PACKAGES_DIR }} /p:PackageVersion=${{ env.VERSION }} /p:Version=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }} /p:InformationalVersion=${{ env.VERSION }}+sha.${GITHUB_SHA:0:7}
      
    - name: Upload packages as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.PACKAGES_DIR }}/
        retention-days: 7

  publish_nuget:
    needs: build
    runs-on: ubuntu-latest
    environment: NuGetOrg
    permissions:
      id-token: write

    steps:

    - name: Download packages artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./
        
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: NuGet push
      run: dotnet nuget push ./*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json  --skip-duplicate
